### ISSUE TITLE
Adicionar README relacionado aos arquivos de manufatura

### ISSUE THREAD

**Issue by patrickelectric** [EME-UFSC/Informacoes#2]
Cada pasta de projeto deve ter um README que informa BOM e tbm as configurações da maquina de operação ou de impressão para impressoras 3D.

**Comment by patrickelectric** [comment]
para as face shields, from @machadoleonardo94:
> 3 perímetros 17% infill. O infill ta ali só pra segurar a casca, porque é quase maciço.
Camada 0.22 55mm/s,
> eu acho configs superestimadas, porque depende muito de altura de camada, velocidade, diametro do bico e os caralho. Por mim só dizer 3 perimetros infill 20% camada 0.22mm velocidade 60mm/s resolve e padroniza

**Comment by patrickelectric** [comment]
>tem gente fazendo com 0.3mm de camada, alguns conseguem, mas a propabilidade de o pessoal fazer algo quebradiço é grande
minha extrusora se peida toda pra fazer 0.3mm nos 40mm/s ou mais rapido

**Comment by rafaellehmkuhl** [comment]
Iniciado em #3
